### ISSUE TITLE
AttributeError: module 'six' has no attribute 'input'

### ISSUE THREAD

**Issue by ankane** [pgxn/pgxnclient#42]
Hi, just wanted to report an exception I came across when trying to load an extension that wasn't installed (in case others run into it).

```sh
pgxn uninstall semver
pgxn load semver
```

Output

```txt
INFO: best version: semver 0.31.1
ERROR: unexpected error
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pgxnclient/cli.py", line 66, in script
    main(args)
  File "/usr/local/lib/python3.9/site-packages/pgxnclient/cli.py", line 34, in main
    run_command(opt, parser)
  File "/usr/local/lib/python3.9/site-packages/pgxnclient/commands/__init__.py", line 129, in run_command
    return opts.cmd(opts, parser=parser).run()
  File "/usr/local/lib/python3.9/site-packages/pgxnclient/commands/install.py", line 498, in run
    self.load_ext(name, sql)
  File "/usr/local/lib/python3.9/site-packages/pgxnclient/commands/install.py", line 521, in load_ext
    self.confirm(
  File "/usr/local/lib/python3.9/site-packages/pgxnclient/commands/__init__.py", line 257, in confirm
    ans = six.input(_("%s [y/N] ") % prompt)
AttributeError: module 'six' has no attribute 'input'
```

Passing `--yes` will skip the prompt and the error.

OS: Mac 11.3
Python version: 3.9.4
Six version: 1.15.0

**Comment by dvarrazzo** [comment]
It looks like it should be `six.moves.input`

**Comment by ankane** [comment]
Thanks @dvarrazzo, that fixed it.
